### PR TITLE
#20: Added item structure

### LINKED ISSUE #20: Implement Item page structure

### PR DESCRIPTION
**Pull request by alexandru-damian**

### CODE REVIEW

**Review by tudorcodrea — CHANGES_REQUESTED** [review]
ratingAverage
ratingCount instead of numberOfRatings

remove listReviews

add reviewStatistic:
{

“itemRatingAverage”: 4.55, (average on all reviews)

“reviewRatingCounts”: [

{ “ratingLevel1”:  40},

{"ratingLevel2": 12},

{"ratingLevel3": 12},

{"ratingLevel4": 12},  --→ if missing then 0

{"ratingLevel5": 70}

]

}

reviewList - paged findbyitemid request

**Review by N-Asadnajafi — DISMISSED** [review]
Everything seems alright to me!

**Review by tudorcodrea — CHANGES_REQUESTED** [review]
please update: //Details 
{ 
 "createdAt": "2021-05-02T08:22:11.839", 
 "modifiedAt": "2021-05-02T08:22:11.839", 
 "createdBy": "00u1cbq0cefmH5Qpo5d6", 
 "modifiedBy": null, 
 "version": 0, 
 "id": "608e613337ff5440e8763989", 
 "name": "Tudor's Coffee", 
 "description": "Tudor does not like coffee though…", 
 "code": "d23d344d-f646-4794-afac-77b06b9b533f", 
 "status": "ACTIVE", 
 "sellerId" : "df5d7a7a-782c-11eb-9439-0242ac130002", 
 "imageUrl":"link of the image for the landing page", 
 "price": "as string", 
 "ratingAverage": 4.5, 
 "reviewRatingCounts":[{ 
 starRatingLevel: 5,  
 reviewCount:12 
 }, 
 { 
 starRatingLevel: 3,  
 reviewCount:34 
 } 
 … 
 ], 
 "media":[ 
   "https://www.shareicon.net/data/128x128/2015/11/01/148242_coffee_256x256.png" 
 ], 
 "labels": [ 
   { 
     "key": "Roasting", 
     "value": "Espresso", 
     "order": 1 
   } 
 ] 
}

**Review by tudorcodrea — DISMISSED** [review]
looks good

**Review by Ose-Me — COMMENTED** [review]
Looks good to me

**Comment by alexandru-damian** [comment]
@Ose-Me, please approve the review if it was considered accepted. Thanks :)

**Review by Ose-Me — APPROVED** [review]
Looks good to me

**Review by Ose-Me — APPROVED** [review]

**Review by N-Asadnajafi — APPROVED** [review]
Everything seems alright to me!

**Pull request merged**
